language: cpp

sudo: required

service:
  - docker

## NOTIFICATIONS
notifications:
  email:
    recipients:
    - florian.davasse@epitech.eu
    on_success: always
    on_failure: always

before_install:
  - docker pull epitechcontent/epitest-docker

jobs:
    include :
        - stage: build
          name: "Build"
          if: branch IN (master, dev)
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make"

        - stage: tests
          name: "Unit Tests"
          if: branch IN (master, dev)
          script:
            - docker run -v $PWD:/app epitechcontent/epitest-docker bash -c "cd app && make fclean && make travis_run"

        - stage: deploy
          name: "Deployement"
          if: branch = master AND type != cron
          before_script:
            - ssh-keyscan git.epitech.eu >> ~/.ssh/known_hosts
            - git checkout master
          script:
            - git push --repo=git@git.epitech.eu:/florian.davasse@epitech.eu/OOP_nanotekspice_2018 --force
